#!/bin/bash
# Script that generates a random insult using a simple adjective + swear + noun formula from three respective dictionaries
# Copyright (C) 2019 Daniel Opdahl (dopdahl16@gmail.com)
# Permission to copy and modify is granted under the GNU General Public License v3.0 license
# Last revised 8/25/19

insult=`shuf -n1  /usr/share/dict/adjectives`" "`shuf -n1  /usr/share/dict/swears`" "`shuf -n1  /usr/share/dict/nouns`
echo $insult