#!/bin/bash
# Script that generates a random word from a dictionary
# Copyright (C) 2019 Daniel Opdahl (dopdahl16@gmail.com)
# Permission to copy and modify is granted under the GNU General Public License v3.0 license
# Last revised 8/25/19

shuf -n1  /usr/share/dict/words
