#!/bin/bash
# Script that generates a random password of user-defined length with the option to exclude certain characters 
# Copyright (C) 2020 Daniel Opdahl (dopdahl16@gmail.com)
# Permission to copy and modify is granted under the GNU General Public License v3.0 license
# Last revised 10/1/20

read -p "How many characters long?: " length
read -p "Characters to exclude (leave empty for none): " excludeChars
validChars='A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~'
if [ ! -z "$excludeChars" ]
then
	validChars=$(echo $validChars | tr -d $excludeChars)
fi
head /dev/urandom | tr -dc $validChars | head -c $length ; echo ''
